version: "3.9"

services:
  ytmusicapi:
    container_name: yt-music-api
    build:
      context: .
      dockerfile: YTMusic-api/Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - YouTube__ApiKey=${YOUTUBE_API_KEY}
      - JwtOptions__SecretKey=${JWT_SECRET_KEY}
      - OptimizerSettings__BaseUrl=http://optimizer:8080
      - ClientSettings__ClientBaseUrl=${CLIENT_BASE_URL}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD}
      - EmailSettings__SenderEmail=${SMTP_SENDER_EMAIL}
      - EmailSettings__SmtpUsername=${SMTP_USERNAME}
    networks:
      - yt-music-api-net
    depends_on:
      - optimizer
    restart: on-failure
  optimizer:
    container_name: yt-music-optimizer
    build:
      context: .
      dockerfile: YTMusicApi.Optimizer/Dockerfile
    networks:
      - yt-music-api-net
    restart: on-failure

networks:
  yt-music-api-net:
    driver: bridge
