// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YTMusicApi.Data;

#nullable disable

namespace YTMusicApi.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260418155820_AddPlaylistIdToOptimizationTask")]
    partial class AddPlaylistIdToOptimizationTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YTMusicApi.Data.MessageBroker.OutboxMessageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("exchange");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("routing_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("YTMusicApi.Data.Optimization.OptimizationTaskDao", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId");

                    b.ToTable("optimization_tasks");
                });

            modelBuilder.Entity("YTMusicApi.Data.Playlist.PlaylistDao", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_title");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("PlaylistId");

                    b.ToTable("playlists");
                });

            modelBuilder.Entity("YTMusicApi.Data.Playlist.PlaylistSettingDao", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Algorithm")
                        .HasColumnType("integer")
                        .HasColumnName("algorithm");

                    b.Property<double>("GenreWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("genre_weight");

                    b.Property<TimeSpan>("TargetDuration")
                        .HasColumnType("interval")
                        .HasColumnName("target_duration");

                    b.HasKey("PlaylistId");

                    b.ToTable("playlist_settings");
                });

            modelBuilder.Entity("YTMusicApi.Data.PlaylistTrack.PlaylistTrackDao", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasColumnType("character varying(34)")
                        .HasColumnName("playlist_id")
                        .HasColumnOrder(0);

                    b.Property<string>("TrackId")
                        .HasColumnType("character varying(11)")
                        .HasColumnName("track_id")
                        .HasColumnOrder(1);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("playlist_tracks");
                });

            modelBuilder.Entity("YTMusicApi.Data.Track.TrackDao", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("track_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_title");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TopicCategories")
                        .HasColumnType("text")
                        .HasColumnName("topic_categories");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("TrackId");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("YTMusicApi.Data.User.UserDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expires");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("YTMusicApi.Data.UserPlaylist.UserPlaylistDao", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PlaylistId")
                        .HasColumnType("character varying(34)")
                        .HasColumnName("playlist_id");

                    b.HasKey("UserId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("user_playlists");
                });

            modelBuilder.Entity("YTMusicApi.Data.Playlist.PlaylistSettingDao", b =>
                {
                    b.HasOne("YTMusicApi.Data.Playlist.PlaylistDao", "Playlist")
                        .WithOne("OptimizationSetting")
                        .HasForeignKey("YTMusicApi.Data.Playlist.PlaylistSettingDao", "PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("YTMusicApi.Data.PlaylistTrack.PlaylistTrackDao", b =>
                {
                    b.HasOne("YTMusicApi.Data.Playlist.PlaylistDao", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YTMusicApi.Data.Track.TrackDao", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("YTMusicApi.Data.UserPlaylist.UserPlaylistDao", b =>
                {
                    b.HasOne("YTMusicApi.Data.Playlist.PlaylistDao", "Playlist")
                        .WithMany("UserPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YTMusicApi.Data.User.UserDao", "User")
                        .WithMany("UserPlaylists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTMusicApi.Data.Playlist.PlaylistDao", b =>
                {
                    b.Navigation("OptimizationSetting");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("UserPlaylists");
                });

            modelBuilder.Entity("YTMusicApi.Data.Track.TrackDao", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("YTMusicApi.Data.User.UserDao", b =>
                {
                    b.Navigation("UserPlaylists");
                });
#pragma warning restore 612, 618
        }
    }
}
